# Generated by Django 4.1.5 on 2023-01-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0004_alter_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='preview',
            field=models.ImageField(auto_created=True, upload_to='preview/'),
        ),
    ]
